runtime: nodejs18
env: standard
service: frontend-service
instance_class: F4

automatic_scaling:
  max_instances: 10

env_variables:
  MONGO_URL: mongodb+srv://bilalhussain199682:Fe5pajztuLM16d3t@mongocrm.yxcn1rw.mongodb.net/TicTacToe_db?retryWrites=true&w=majority&appName=MongoCRM
  SECRET: tictactoe
  NODE_ENV: production