#app.yaml for GAE
runtime: python39
env: standard
service: default

entrypoint: gunicorn -b :8080 Flask_app:app --workers 8 --threads 4 --timeout 120 --preload

automatic_scaling:
  max_instances: 5

env_variables:
  STRESS_MODE: on
