apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: gcr.io/acs-project-458806/backend-service
        ports:
        - containerPort: 8080
        env:
        - name: STRESS_MODE
          value: "on"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: backend-service
  ports:
  - port: 80
    targetPort: 8080
